import Provider from '@/providers/Provider';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

const mont = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Find Stocks',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={mont.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
